### ISSUE TITLE
driftCorrection feature request: driftCorrectInter(SMD1,SMD2)

### ISSUE THREAD

**Issue by kalidke** [LidkeLab/smite#13]
would like a static method that can find cost and offset between coorindates in two SMD structures.  It would then be nice if this was used inside driftCorrectInter.

**Comment by MJWester** [comment]
[delta12, Statistics] = smi_core.DriftCorrection.regViaDC(SMD1, SMD2);

finds the shift between two SMD structures and returns the inter-dataset cost in the Statistics output structure.  David added driftCorrectBF functions as well to use his brightfield strategy for drift correction.
