### ISSUE TITLE
JOSS Review: Check contributors

### ISSUE THREAD

**Issue by bencardoen** [LidkeLab/smite#38]
As part of the JOSS [review](https://github.com/openjournals/joss-reviews/issues/5563), I have to verify this

```
Contribution and authorship: Has the submitting author (@MJWester) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
```

I can see that this holds for @MJWester , but the paper.md lists 13 authors, yet the repo has 8 contributors. 
Can you please clarify in the paper what contributions the other authors made (funding, support, testing, ...)

Thanks, 

Ben

**Comment by MJWester** [comment]
The development of the SMITE software has taken place over several years,
including an early period before our use of GitHub.  Each of the authors
has made a contribution to SMITE which I summarize below (and will now
include in the paper).  In the process of making this list, we added three
more authors as we think it is important that anyone that developed software
for SMITE be recognized.  I hope that this list is not too long, but SMITE
is a big package with many pieces and many contributors.

# Author Contributions

KAL conceived and supervised development of SMITE and its predecessors.
DJS, MF, HMF, MBMM and KAL coded SR localization techniques.
SP, MJW, MF and HMF implemented thresholding.
DJS and HMF wrote frame connection.
MJW, KAL and DJS developed drift correction based on an earlier version by FF.
MF and KAL devloped BaGoL; MJW wrote the interface to SMITE.
DJS, HMF, WKK, DAR and EJ designed and wrote code for single particle tracking
based on ideas from PKR.
DJS, MBMM, HMF and SP created visualizations.
SK, MJW and DJS added SMLM and SPT simulations.
KAL, SL and MJW developed Zernike polynomial point spread function engineering.
MJW packaged clustering techniques, and
SLS and MJW wrote code for various cluster statistics.
DJS added channel registration, various statistics, dimer hidden Markov
modeling and the batch Publish class.
PKR and MJO developed the diffusion estimator, while MJO also contributed to
the change detector.
MJW, SK and EAB added GitHub documentation.
MJW and DJS wrote the manuscript.
All authors reviewed the manuscript.

**Comment by bencardoen** [comment]
Thank you for clarifying the contributions and listing credit in detail.
