### ISSUE TITLE
JOSS Review: Make tests automatic/online

### ISSUE THREAD

**Issue by bencardoen** [LidkeLab/smite#42]
[JOSS Review](https://github.com/openjournals/joss-reviews/issues/5563)

It is commendable to provide unit-tests, but I would strongly suggest making these integrated in e.g. Travis/Circle CI. 
For OSS packages the CCI free minutes would be sufficient. 

See https://circleci.com/developer/orbs/orb/mathworks/matlab for how to run matlab on CCI. 
Compiling C also works on CCI if needed.

**Comment by MJWester** [comment]
Thank you for the suggestion.  We have installed CI using GitHub Actions, and
are currently integrating our unitTests into this framework.  However, many of
our tests require a GPU, which is not available on a GitHub-Hosted Runner.  Our
network configuration consists of various Windows and a small number of Linux
systems, so we are trying to best decide how to go about adding CI while
providing flexibility of system usage to our developers.  Currently, we are
skipping tests if they require a GPU and one is not available.

I will be traveling for 3-weeks (back early August), so will revisit this issue
on my return, for example, moving to a different CI, but this should be much
easier now that we got the hang of this process.

**Comment by MJWester** [comment]
A if no gpu: then mask test y would be perfectly fine.

is basically how I set up the automated tests requiring a GPU:

   if gpuDeviceCount > 0
      do test needing a GPU
   else
      skip test
   end

Installing a local runner is more complicated, so we will mull on that, especially as it requires a spare machine as you note.  And although not automated, we can run the GPU tests manually, at least for now (the first two unitTests are the most important as they exercise most of the basic functionality).  Certainly, for future projects, we will set up automated testing.
