### ISSUE TITLE
JOSS Review: Difficulties with Installation and CUDA Compilation Error

### ISSUE THREAD

**Issue by ajinkyakadu** [LidkeLab/smite#43]
I am currently reviewing the smite code for JOSS and encountered several issues during the installation and setup. Here are the details:

1. **Installation Steps:** The installation process could be made more straightforward. Currently, after cloning the repository, there's an additional step to compile mex files and possibly the CUDA files, depending on the machine's architecture. This step is not particularly intuitive, especially for newcomers or users unfamiliar with MATLAB's mexing process.

2. **CUDA Compilation Error:** While attempting to compile the CUDA files, I encountered the following error multiple times:

   ` nvcc fatal   : Cannot find compiler 'cl.exe' in PATH`

    This error appeared when trying to compile `smi_cuda_gaussMLEv2`, `smi_cuda_FindROI`, and `smi_cuda_PSFSample3DBlob`. I'm using MATLAB R2022b on Windows 11 with NVIDIA GeForce RTX 3090 (ComputeCapability: '8.6').

**Recommendations:**
1. Consider improving the installation instructions to make them more intuitive, potentially with an automated script.
2. For the CUDA error, it seems like the compiler cannot find 'cl.exe'. This might be related to the setup of the CUDA environment and the Visual Studio installation. Ensure that the necessary compilers are correctly set in the PATH or provide clear instructions for users on how to do this.

Thank you for your attention to these issues. I look forward to seeing the improvements and continuing with the review.

**Comment by MJWester** [comment]
Thank you for your comments.  First of all, the distribution contains compiled versions of the mex codes for Linux and Windows (I just added MacOS), all 64 bit, as well as the CUDA codes (the ptx files are a low level architecture independent format), but this is not clear from the instructions, I agree.  In theory, most users should not have to compile anything by hand.  The installation instructions have been reorganized and expanded to make this clearer.

With regards to the error with cl.exe, the PATH in Windows must contain the directory of binaries for the NVIDIA GPU Computing Toolbox AND for the Visual Studio installation (where cl.exe is located), examples of which are provided in cuda_Make.  The instructions in cuda_Make have been expanded.

**Comment by MJWester** [comment]
Thank you for your comments.  I apologize for the delay in responding as your issues prompted further examination on our own about how to handle them, especially CUDA.

First of all, the distribution contains compiled versions of the mex codes for Linux and Windows (I just added MacOS), all 64 bit, as well as the CUDA codes (the ptx files are a low level architecture independent format), but this is not clear from the instructions, I agree.  In theory, most users should not have to compile anything by hand.  The installation instructions have been reorganized and expanded to make this clearer.  The make scripts have also been more heavily commented.

It is not so easy to make the installation process completely automated, especially for Windows, if recompilation is needed (which should be rare; we did test SMITE on various machines with compute capability 5.0 to 8.6 using the updated mex and ptx files that are provided in the development version).  We will continue to make the installation process clearer, but each machine is different, so especially with CUDA + Visual Studio, it is hard to generalize. However, MATLAB is making mex file setup nearly automatable, so hopefully they will do the same for CUDA.

With regards to the error with cl.exe, the PATH in Windows must contain the directory of binaries for the NVIDIA GPU Computing Toolbox AND for the Visual Studio installation (where cl.exe is located), examples of which are provided in cuda_Make.  Also, you need relatively new versions of the CUDA driver (we tried 11.7 and 12.2) and Visual Studio (2019 
community worked for us).  Again, most users will be able to used the compiled files unchanged as is the case at
our university.

**Comment by ajinkyakadu** [comment]
Thank you for clarifying the installation process and addressing the CUDA issues. I've checked the updates, and the issue is now resolved. Thanks for your quick action.
