### ISSUE TITLE
Hard-coded Paths in Example Scripts

### ISSUE THREAD

**Issue by ajinkyakadu** [LidkeLab/smite#44]
During my review of the ***smite*** code for JOSS, I found that many paths in the example scripts are hard-coded, making it difficult for users to run the examples out of the box without modification. 

For instance, in `Example_SPTBatch.m`, there's a specific line:
```matlab
FiducialDir = 'C:\Users\David\Documents\GitHub\smite\MATLAB\examples\example_data\spt\multiple_files\fiducial';
```
The hard-coded path indicates that the repository's name and location are user-specific, which will lead to errors if another user tries to run the script without any changes.

I've noticed similar issues in several other example scripts as well.

### Recommendation:

Please consider making the paths in the example scripts relative or dynamically generated based on the current location of the script. This would ensure that users can seamlessly run the provided examples without the need for manual modifications.

**Comment by MJWester** [comment]
Actually, the example you cite was changed some 3 months ago according to GitHub, so you are running an old version of the repository before many fixes were made during the earlier portion of the review process.  However, your comment is on target as there are certainly examples that have hard-coded pathnames, which while convenient for our local users, are not appropriate for a public distribution.  The hard-coded paths have been removed or commented out.  To make it clear when user supplied locations are needed in a few places, the string 'NEEDS_TO_BE_SET!' is assigned to variables holding user file paths.

The current version of SMITE has both self-contained examples where no user modification is required (required file paths refer to generated temporary directories using the MATLAB command tempdir), and example code templates where some file paths must be specified by the user.  There are also unit tests for most of the classes requiring no user changes.  The README.md file in the examples directory lists which files belong to each category (example, template or how to invoke an unitTest).

Also, you should use the development version of SMITE for this review, as we prefer to wait to put out a new release until the review process is concluded. We have now added a version string to indicate what release of SMITE is installed when setupSMITE occurs.

Thank you for your comments.

**Comment by ajinkyakadu** [comment]
Thank you for the update. I checked the new version and the issue with hard-coded paths is fixed. Great job and thanks for the quick response.
